[pytest]
minversion = 8.0
required_plugins = pytest-asyncio
asyncio_mode = auto
filterwarnings =
    ignore:authlib\.jose module is deprecated, please use joserfc instead\.:authlib.deprecate.AuthlibDeprecationWarning:authlib\._joserfc_helpers
markers =
    asyncio: mark test as asyncio
