"""Backend-owned analytics events for Similar Search."""

from __future__ import annotations

from collections.abc import Callable
from datetime import datetime, timezone
from uuid import uuid4

from pydantic import AnyUrl, TypeAdapter, ValidationError

from src.domain.similar_search import (
    SimilarSearchClickAnalyticsResponse,
    SimilarSearchClickEvent,
    SimilarSearchClickEventRequest,
    SimilarSearchClickEventResponse,
)
from src.use_cases.similar_search.ports import SimilarSearchClickEventRepositoryPort


class SimilarSearchClickEventRejected(Exception):
    """Raised when a click event points to an unsafe or unsupported target."""

    def __init__(self, *, safe_code: str, message: str) -> None:
        """Store a safe machine code and user-facing message."""

        super().__init__(message)
        self.safe_code = safe_code
        self.message = message


class SimilarSearchClickEventService:
    """Record product interest generated by free Similar Search."""

    def __init__(
        self,
        *,
        repository: SimilarSearchClickEventRepositoryPort,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        """Store dependencies for click-event persistence."""

        self._repository = repository
        self._clock = clock or (lambda: datetime.now(timezone.utc))
        self._url_adapter = TypeAdapter(AnyUrl)

    async def record_click(self, request: SimilarSearchClickEventRequest) -> SimilarSearchClickEventResponse:
        """Persist a click event and return the safe redirect decision."""

        redirect_url = self._validated_external_redirect_url(request.offer_url)
        event = SimilarSearchClickEvent(
            event_id=f"similar_click_{uuid4().hex}",
            product_id=request.product_id,
            title=request.title,
            marketplace=request.marketplace,
            offer_url=request.offer_url,
            image_url=request.image_url,
            user_country_code=request.user_country_code.upper() if request.user_country_code else None,
            user_city=request.user_city,
            source=request.source,
            redirect_allowed=redirect_url is not None,
            created_at=self._clock(),
        )
        saved = await self._repository.save_click_event(event)
        return SimilarSearchClickEventResponse(
            event_id=saved.event_id,
            redirect_url=redirect_url,
            redirect_allowed=saved.redirect_allowed,
        )

    async def get_analytics(self, *, limit: int = 10) -> SimilarSearchClickAnalyticsResponse:
        """Return aggregate click analytics for admin review."""

        safe_limit = min(max(int(limit), 1), 50)
        return await self._repository.get_click_analytics(limit=safe_limit)

    def _validated_external_redirect_url(self, offer_url: str) -> str | None:
        """Return an external redirect URL or None for local-only catalog records."""

        normalized = offer_url.strip()
        if normalized.startswith("local://business-catalog/"):
            return None
        try:
            parsed = self._url_adapter.validate_python(normalized)
        except ValidationError as exc:
            raise SimilarSearchClickEventRejected(
                safe_code="similar_search_offer_url_invalid",
                message="Product link is not valid.",
            ) from exc
        if parsed.scheme not in {"http", "https"}:
            raise SimilarSearchClickEventRejected(
                safe_code="similar_search_offer_url_scheme_blocked",
                message="Product link scheme is not allowed.",
            )
        return str(parsed)
