"""Dataset for the AI FitFabrica site structure PDF."""

from __future__ import annotations

PAGES = [
    {
        "route": "/",
        "title": "Главная",
        "contour": "Public",
        "layout": "public",
        "purpose": "Главный вход в продукт: объясняет, что FitFabrica объединяет примерку, fashion-workflows и контент в одном сервисе.",
        "blocks": ["Hero", "Разделение контуров B2C/B2B", "Возможности", "Процесс", "Финальный CTA"],
        "buttons": ["Для себя → /for-you", "Для бизнеса → /business", "Открыть workspace → /workspace", "Запросить демо → /contacts"],
        "sources": [
            "apps/web/src/app/(public)/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages.ts",
        ],
    },
    {
        "route": "/for-you",
        "title": "Для себя",
        "contour": "Public",
        "layout": "public",
        "purpose": "B2C-страница: объясняет, как пользователь примеряет вещь до покупки и снижает риск ошибочного заказа.",
        "blocks": ["Hero", "Ключевые действия для пользователя", "Аргументы пользы", "CTA на запуск примерки"],
        "buttons": ["Начать примерку → /workspace/try-on/new"],
        "sources": [
            "apps/web/src/app/(public)/for-you/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages.ts",
        ],
    },
    {
        "route": "/business",
        "title": "Для бизнеса",
        "contour": "Public",
        "layout": "public",
        "purpose": "B2B-страница: показывает FitFabrica как рабочий инструмент для команды, каталога, карточек товара и контента.",
        "blocks": ["Hero", "Что получает команда", "Сценарии использования", "CTA на демо"],
        "buttons": ["Запросить демо → /contacts"],
        "sources": [
            "apps/web/src/app/(public)/business/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages.ts",
        ],
    },
    {
        "route": "/capabilities",
        "title": "Возможности",
        "contour": "Public",
        "layout": "public",
        "purpose": "Инвентарь продуктовых модулей: показывает, что сервис построен из рабочих сценариев, а не из случайных промо-экранов.",
        "blocks": ["Hero", "Список capability-групп", "Описание модулей", "CTA"],
        "buttons": ["Переходы по основным CTA внутри страницы"],
        "sources": [
            "apps/web/src/app/(public)/capabilities/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages.ts",
        ],
    },
    {
        "route": "/how-it-works",
        "title": "Как работает",
        "contour": "Public",
        "layout": "public",
        "purpose": "Объясняет backend-first логику: frontend собирает ввод и показывает состояние, backend исполняет workflow.",
        "blocks": ["Hero", "Пошаговый процесс", "Раздел ответственности frontend/backend", "CTA"],
        "buttons": ["CTA на рабочий сценарий или демо"],
        "sources": [
            "apps/web/src/app/(public)/how-it-works/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages.ts",
        ],
    },
    {
        "route": "/pricing",
        "title": "Тарифы",
        "contour": "Public",
        "layout": "public",
        "purpose": "Показывает структуру тарифов как продуктовую рамку, подготовленную для backend billing.",
        "blocks": ["Hero", "Планы Start / Studio / Enterprise", "Описание различий", "CTA на обсуждение подключения"],
        "buttons": ["Обсудить подключение → /contacts"],
        "sources": [
            "apps/web/src/app/(public)/pricing/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages-extra.ts",
        ],
    },
    {
        "route": "/privacy",
        "title": "Безопасность",
        "contour": "Public",
        "layout": "public",
        "purpose": "Описывает приватность и архитектурную дисциплину: secrets не во frontend, typed DTO, подготовка к разделению доступа.",
        "blocks": ["Hero", "Принципы приватности", "Архитектурные гарантии", "Дополнительные пояснения"],
        "buttons": ["Футерная навигация на связанные страницы"],
        "sources": [
            "apps/web/src/app/(public)/privacy/page.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/lib/content/public-pages-extra.ts",
        ],
    },
    {
        "route": "/contacts",
        "title": "Контакты / Демо",
        "contour": "Public",
        "layout": "form",
        "purpose": "Страница запроса демо и обсуждения интеграции. Содержит рабочую frontend-форму с typed API-контрактом.",
        "blocks": ["Hero", "Visual placeholder", "Форма: компания, имя, email, сайт/задача", "Success / error state"],
        "buttons": ["Отправить заявку → submit на той же странице"],
        "sources": [
            "apps/web/src/app/(public)/contacts/page.tsx",
            "apps/web/src/features/public/contact-form.tsx",
            "apps/web/src/components/ui/form-field.tsx",
            "apps/web/src/lib/api/client.ts",
        ],
    },
    {
        "route": "/sign-in",
        "title": "Вход",
        "contour": "Public",
        "layout": "form",
        "purpose": "Страница входа в рабочее пространство. Сейчас готовит email/password flow и будущую интеграцию с backend-auth.",
        "blocks": ["Форма входа", "Email", "Пароль", "Success / error state", "Правый visual placeholder"],
        "buttons": ["Войти по email → submit на той же странице", "Продолжить с Google → disabled"],
        "sources": [
            "apps/web/src/app/(public)/sign-in/page.tsx",
            "apps/web/src/features/public/sign-in-form.tsx",
            "apps/web/src/components/ui/form-field.tsx",
            "apps/web/src/lib/api/client.ts",
        ],
    },
    {
        "route": "/workspace",
        "title": "Кабинет",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Главная точка входа в рабочий кабинет: показывает, куда идти дальше, и не превращает кабинет в хаотичный dashboard.",
        "blocks": ["Sidebar", "Hero рабочего кабинета", "Статусы", "Placeholder рабочей зоны", "AI checklist", "Нижние панели"],
        "buttons": ["Новая примерка → /workspace/try-on/new", "История → /workspace/history"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
            "apps/web/src/components/navigation/workspace-sidebar.tsx",
        ],
    },
    {
        "route": "/workspace/try-on/new",
        "title": "Новая примерка",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Вход в try-on workflow: собирает фото человека и одежды, показывает ожидания к входным данным и готовит запуск генерации.",
        "blocks": ["Sidebar", "Hero", "Upload / preview zone", "AI status panel", "Checklist проверки", "Нижние product-panels"],
        "buttons": ["Сгенерировать примерку → disabled/логика workflow", "Открыть результат → /workspace/try-on/result"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/try-on/new/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
            "apps/web/src/components/navigation/workspace-sidebar.tsx",
        ],
    },
    {
        "route": "/workspace/try-on/result",
        "title": "Результат примерки",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Показывает итог try-on: один основной результат, AI-проверки качества и следующие действия пользователя.",
        "blocks": ["Sidebar", "Result hero", "Главный preview", "AI checklist", "Панели действий"],
        "buttons": ["Продолжить в подбор образа → /workspace/outfit-builder", "Сохранить в историю → /workspace/history"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/try-on/result/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
        ],
    },
    {
        "route": "/workspace/outfit-builder",
        "title": "Подбор образа",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Сценарий сборки образа: превращает одну вещь или результат примерки в полноценный lookboard и рекомендации.",
        "blocks": ["Sidebar", "Hero", "Look preview", "Style rules", "Follow-up actions"],
        "buttons": ["Вернуться к результату → /workspace/try-on/result", "Искать альтернативы → /workspace/similar"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/outfit-builder/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
        ],
    },
    {
        "route": "/workspace/similar",
        "title": "Найти похожее",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Поиск похожих и более выгодных альтернатив: разделяет источник, match-логику, фильтры и будущий список результатов.",
        "blocks": ["Sidebar", "Hero", "Result list placeholder", "Compare panel", "Price guidance"],
        "buttons": ["Начать новый поиск → /workspace/try-on/new", "Открыть историю → /workspace/history"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/similar/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
        ],
    },
    {
        "route": "/workspace/product-card",
        "title": "Карточка товара",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Workflow создания коммерческой карточки товара: от исходников и атрибутов к структурированному товарному описанию и визуалу.",
        "blocks": ["Sidebar", "Hero", "Card structure", "AI support", "Operational handoff"],
        "buttons": ["Открыть контент-пакет → /workspace/content-package", "Настроить бренд → /workspace/business-profile"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/product-card/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages.ts",
        ],
    },
    {
        "route": "/workspace/content-package",
        "title": "Контент-пакет",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Собирает публикационные материалы в единый пакет: визуалы, copy, заметки и готовность к экспорту.",
        "blocks": ["Sidebar", "Hero", "Package overview", "AI notes", "Export rail"],
        "buttons": ["Вернуться к товару → /workspace/product-card", "Сохранить в историю → /workspace/history"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/content-package/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
    },
    {
        "route": "/workspace/style-profile",
        "title": "Профиль стиля",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Экран будущих персональных предпочтений: хранит стиль, fit-настройки, палитру и ограничения пользователя.",
        "blocks": ["Sidebar", "Hero", "Preference form zone", "Preview context", "Traceability"],
        "buttons": ["Вернуться к примерке → /workspace/try-on/new", "Перейти к образу → /workspace/outfit-builder"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/style-profile/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
    },
    {
        "route": "/workspace/business-profile",
        "title": "Профиль бизнеса",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Хранит контекст бренда, правила контента и каналы публикации, не смешивая их с отдельными workflow-страницами.",
        "blocks": ["Sidebar", "Hero", "Profile editor", "Operational rules", "Publishing readiness"],
        "buttons": ["Вернуться к товару → /workspace/product-card", "Обсудить интеграцию → /contacts"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/business-profile/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
    },
    {
        "route": "/workspace/credits",
        "title": "Кредиты и баланс",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Выделенная страница баланса и правил списания, подготовленная под backend-billing без бизнес-логики во frontend.",
        "blocks": ["Sidebar", "Hero", "Balance panel", "Usage history", "Top-up flow"],
        "buttons": ["Открыть тарифы → /pricing", "Посмотреть историю → /workspace/history"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/credits/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
    },
    {
        "route": "/workspace/history",
        "title": "История и проекты",
        "contour": "Workspace",
        "layout": "workspace",
        "purpose": "Хранит завершенные сценарии, статусы и повторный доступ к результатам, вместо случайного списка-черновика.",
        "blocks": ["Sidebar", "Hero", "History rail", "Selected item preview", "Operational audit"],
        "buttons": ["Новый запуск → /workspace/try-on/new", "Вернуться на главную → /workspace"],
        "sources": [
            "apps/web/src/app/(workspace)/workspace/history/page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
    },
]

FILE_GROUPS = [
    {
        "group": "Текст и смысл страниц",
        "items": [
            "apps/web/src/lib/content/public-pages.ts",
            "apps/web/src/lib/content/public-pages-extra.ts",
            "apps/web/src/lib/content/workspace-pages.ts",
            "apps/web/src/lib/content/workspace-pages-extra.ts",
        ],
        "note": "Здесь лежат заголовки, описания, CTA, статусы и логика смыслового наполнения большинства страниц.",
    },
    {
        "group": "Маршруты и навигация",
        "items": [
            "apps/web/src/lib/routes/public-routes.ts",
            "apps/web/src/lib/routes/workspace-routes.ts",
            "apps/web/src/components/navigation/public-header.tsx",
            "apps/web/src/components/navigation/public-footer.tsx",
            "apps/web/src/components/navigation/workspace-sidebar.tsx",
        ],
        "note": "Эти файлы задают состав меню, ссылки, footer-связи и навигацию workspace.",
    },
    {
        "group": "Размещение блоков и layout",
        "items": [
            "apps/web/src/app/layout.tsx",
            "apps/web/src/app/(workspace)/workspace/layout.tsx",
            "apps/web/src/features/public/public-page.tsx",
            "apps/web/src/features/workspace/workspace-page.tsx",
        ],
        "note": "Здесь задается общий каркас страниц: hero, сетки, сайдбар, рабочая область и layout-механика.",
    },
    {
        "group": "Стили, цвета, отступы, кнопки",
        "items": [
            "apps/web/src/app/globals.css",
            "apps/web/src/components/ui/button-link.tsx",
            "apps/web/src/components/ui/form-field.tsx",
            "apps/web/src/components/ui/form-textarea.tsx",
        ],
        "note": "Главный файл внешнего вида сайта — globals.css. Там лежат цветовые переменные, типографика, spacing и базовые классы.",
    },
    {
        "group": "Картинки и визуальные заглушки",
        "items": [
            "apps/web/src/components/ui/visual-placeholder.tsx",
            "apps/web/public/site/screens/*.png",
        ],
        "note": "В проекте есть набор screen-изображений и отдельный компонент визуальной заглушки. Выделенного production-каталога real assets пока нет.",
    },
    {
        "group": "Формы и API-подключение",
        "items": [
            "apps/web/src/features/public/contact-form.tsx",
            "apps/web/src/features/public/sign-in-form.tsx",
            "apps/web/src/lib/api/client.ts",
            "apps/web/src/lib/api/contracts.ts",
        ],
        "note": "Эти файлы отвечают за submit, typed DTO и вызовы backend для demo request и sign-in.",
    },
    {
        "group": "Шрифты",
        "items": [
            "apps/web/src/app/globals.css",
        ],
        "note": "Сейчас отдельного локального font-file слоя не заведено. Шрифтовые стековые правила заданы прямо в CSS-переменных --font-sans и --font-display.",
    },
]
